### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by irwin-chen** [irwin-chen/driving-game#3]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create main.js file
- [x] link js file to main html file
- [x] add event listener for keystrokes
- [x] create function that turns car left, right, or around depending on keystroke (left,right,down)
- [x] add a transition to car
