### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by irwin-chen** [irwin-chen/driving-game#5]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] add location to hold car's x and y coordinates on page
- [x] use absolute positioning to position element
- [x] create an event listener to listen for the spacebar to start the car
- [x] create a function with to move the car's position along the page 
- [x] set an interval every 16 ms to move the car along the page
